const typingText = "In the tranquil village of Tanalur, nestled within Kerala's lush landscape, an extraordinary tale unfolded that would challenge the boundaries of human understanding and perception. Dr. Arjun Menon, a renowned quantum physicist with piercing eyes and a mind that constantly traversed the intricate labyrinths of scientific exploration, had dedicated his entire professional career to unraveling the mysterious connections between consciousness, quantum mechanics, and the fundamental fabric of reality. His research, which had initially been met with skepticism by his academic peers, gradually gained recognition as he meticulously documented phenomena that seemed to defy conventional scientific paradigms. The research facility he had established on the outskirts of the village was a marvel of modern architectural design, blending seamlessly with the surrounding tropical environment. Its glass-and-steel structure reflected the verdant greenery, creating an illusion of transparency that mirrored Menon's philosophical approach to scientific inquiry. Inside this cutting-edge laboratory, an array of sophisticated equipment hummed with potential, each instrument calibrated to detect the most minute variations in quantum states and electromagnetic fields. Menon's current project focused on exploring the potential interconnectedness of human consciousness with quantum entanglement, a concept that had fascinated theoretical physicists for decades. He hypothesized that human thoughts and emotions might possess quantum properties that could potentially influence physical reality in ways not yet comprehended by mainstream scientific understanding. This radical proposition challenged centuries of established scientific thought, suggesting that consciousness was not merely a byproduct of neurological processes but potentially a fundamental force of the universe. His team of researchers, a diverse group of international scientists who had been drawn to his groundbreaking work, represented various disciplines: neuroscientists, quantum physicists, mathematicians, and computational experts. Each brought unique perspectives and methodological approaches, creating a collaborative environment that thrived on intellectual curiosity and rigorous empirical investigation. The primary experimental setup involved a series of intricate quantum entanglement experiments designed to test the potential correlation between human intentionality and quantum system behavior. Participants would be placed in carefully controlled environments, their brain activity monitored through advanced neuroimaging techniques while simultaneously tracking quantum particle interactions in isolated chambers. The goal was to detect any statistically significant deviations from expected random quantum fluctuations that might suggest a conscious influence. Dr. Elena Rodriguez, a brilliant neuroscientist from Barcelona who had joined Menon's team two years earlier, had developed sophisticated algorithms capable of analyzing the complex datasets generated by these experiments. Her computational models could detect subtle patterns and correlations that would be imperceptible through traditional statistical analysis. Her background in both neuroscience and quantum information theory made her an invaluable asset to the research team. The village of Tanalur itself played an unexpected role in this scientific endeavor. Its unique geographical location, characterized by specific geological formations and electromagnetic characteristics, seemed to provide an ideal environment for conducting sensitive quantum experiments. Local indigenous knowledge, passed down through generations, spoke of the area possessing unusual energetic properties, a claim that Menon found intriguingly compatible with his scientific investigations. Funding for the research came from a combination of private philanthropic foundations interested in frontier scientific exploration, government research grants, and strategic partnerships with international academic institutions. The multidisciplinary nature of the project attracted significant attention from the global scientific community, with researchers and philosophers eagerly anticipating potential breakthrough publications. Ethical considerations were paramount in their experimental design. Strict protocols ensured participant safety, informed consent, and rigorous data protection. The research team maintained transparent communication about their methodologies, understanding that groundbreaking scientific work required not just intellectual rigor but also public trust and comprehension. As the experiments progressed, preliminary data began revealing tantalizing hints of phenomena that defied conventional explanations. Certain experimental runs showed statistically significant correlations between participant mental states and quantum system behaviors, suggesting the possibility of a deeper, yet unexplored connection between consciousness and fundamental physical processes.";
const page1 = document.getElementById('page1');
const page2 = document.getElementById('page2');
const congratsPage = document.getElementById('congratsPage');
const userInput = document.getElementById('userInput');
const result = document.getElementById('result');
const timerDisplay = document.getElementById('timer');
const congratsMessage = document.getElementById('congratsMessage');
const finalResult = document.getElementById('finalResult');
const accuracyDisplay = document.getElementById('accuracyDisplay');
const mistakesDisplay = document.getElementById('mistakesDisplay');

let correctChars = 0;
let totalChars = typingText.length;
let mistakes = 0;
let timer;
let timeLeft = 15 * 60; // 15 minutes in seconds

function goToPage2() {
  const name = document.getElementById('name').value.trim();
  const course = document.getElementById('course').value.trim();

  if (name === "" || course === "") {
    alert("Please fill in your name and course!");
    return;
  }

  page1.style.display = "none";
  page2.style.display = "block";
  userInput.disabled = false; // Enable typing area

  const userNameDisplay = document.getElementById('userNameDisplay');
  userNameDisplay.innerHTML = `Hello, <strong>${name}</strong>! Start typing the text below:`;

  startTimer();
}

function startTimer() {
  timer = setInterval(() => {
    if (timeLeft <= 0) {
      clearInterval(timer);
      userInput.disabled = true;
      result.innerHTML = "<h3>Time's up!</h3><p>Your results have been recorded.</p>";
    } else {
      timeLeft--;
      updateTimerDisplay();
    }
  }, 1000);
}

function updateTimerDisplay() {
  const minutes = Math.floor(timeLeft / 60);
  const seconds = timeLeft % 60;
  timerDisplay.textContent = `Time Left: ${minutes}:${seconds < 10 ? "0" + seconds : seconds}`;
}

function checkTyping() {
  const typedText = userInput.value;
  const currentCharIndex = typedText.length - 1;

  if (currentCharIndex < 0) {
    return; // Avoid checking when nothing is typed
  }

  const currentChar = typedText[currentCharIndex];
  const expectedChar = typingText[currentCharIndex];

  // Check if the current character is correct
  if (currentChar === expectedChar) {
    correctChars++;
    // Highlight correct input in green
    userInput.style.backgroundColor = "#eaffea"; // Light green
  } else {
    mistakes++;
    // Remove incorrect character and provide feedback
    userInput.value = typedText.slice(0, -1); // Remove last incorrect character
    userInput.style.backgroundColor = "#ffe6e6"; // Light red
  }

  // Update live statistics
  updateStats();

  // End typing when the entire text matches
  if (typedText === typingText) {
    clearInterval(timer);
    showCongratulations();
  }
}

function updateStats() {
  const accuracy = ((correctChars / (correctChars + mistakes)) * 100).toFixed(2);
  accuracyDisplay.textContent = `Accuracy: ${accuracy}%`;
  mistakesDisplay.textContent = `Mistakes: ${mistakes}`;
}

function submitTyping() {
  clearInterval(timer); // Stop the timer
  userInput.disabled = true; // Disable typing

  const accuracy = ((correctChars / (correctChars + mistakes)) * 100).toFixed(2);

  result.innerHTML = `
    <h3>Results</h3>
    <p><strong>Correct Characters:</strong> ${correctChars}</p>
    <p><strong>Incorrect Characters:</strong> ${mistakes}</p>
    <p><strong>Accuracy:</strong> ${accuracy}%</p>
  `;
}

function showCongratulations() {
  const name = document.getElementById('name').value.trim();
  const course = document.getElementById('course').value.trim();

  page2.style.display = "none";
  congratsPage.style.display = "block";

  const accuracy = ((correctChars / (correctChars + mistakes)) * 100).toFixed(2);

  congratsMessage.innerHTML = `Congratulations <strong>${name}</strong> from <strong>${course}</strong>! You have perfectly completed the typing competition.`;
  finalResult.innerHTML = `
    <h3>Your Results</h3>
    <p><strong>Correct Characters:</strong> ${correctChars}</p>
    <p><strong>Incorrect Characters:</strong> ${mistakes}</p>
    <p><strong>Accuracy:</strong> ${accuracy}%</p>
  `;
}

// Disable pasting in the input field
userInput.addEventListener('paste', (e) => {
  e.preventDefault();
  alert("Pasting is not allowed!");
});
